# Generated by Django 5.2.6 on 2025-10-21 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_remove_payout_paid_remove_realproprequest_approved_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mt5account',
            name='account_size',
            field=models.CharField(choices=[('$5k', '$5k'), ('$10k', '$10k'), ('$25k', '$25k'), ('$50k', '$50k')], default='$5k', max_length=10),
        ),
    ]
