# Generated by Django 5.2.6 on 2025-11-01 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_customuser_password_reset_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mt5account',
            name='daily_max_drawdown',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='mt5account',
            name='equity_open_day',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='mt5account',
            name='equity_open_day_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
