# Generated by Django 5.2.6 on 2025-11-01 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_mt5account_daily_max_drawdown_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payout',
            name='bank_details',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='payout',
            name='wallet_address',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
