# Generated by Django 5.2.6 on 2025-11-01 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_payout_bank_details_payout_wallet_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='mt5account',
            name='account_type',
            field=models.CharField(choices=[('trial', 'Trial'), ('funded_phase_1', 'Funded Phase 1'), ('funded_phase_2', 'Funded Phase 2'), ('funded_live', 'Live Funded')], default='trial', max_length=20),
        ),
    ]
