# Generated by Django 5.2.6 on 2025-12-16 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_globalalert'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='link_text',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='announcement',
            name='link_url',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
