# Generated by Django 5.2.6 on 2026-01-10 16:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_referralsettings_customuser_referral_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payout',
            name='account_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='payout',
            name='bank_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='payout',
            name='full_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='payout',
            name='payout_type',
            field=models.CharField(choices=[('trading', 'Trading Account'), ('referral', 'Referral Commission')], default='trading', max_length=20),
        ),
        migrations.AlterField(
            model_name='payout',
            name='mt5_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payouts', to='main.mt5account'),
        ),
    ]
