# Generated by Django 5.2.6 on 2026-01-16 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_discountcode'),
    ]

    operations = [
        migrations.CreateModel(
            name='VerifiedTrader',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
                ('date_passed', models.DateField()),
                ('account_size', models.CharField(max_length=20)),
                ('prop_account_purchased', models.CharField(max_length=100)),
                ('interviewed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
