# Generated by Django 5.2.6 on 2026-01-17 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_verifiedtrader'),
    ]

    operations = [
        migrations.AddField(
            model_name='verifiedtrader',
            name='interview_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
