# Generated by Django 5.2.6 on 2026-01-17 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_verifiedtrader_interview_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='mt5account',
            name='breach_reason',
            field=models.TextField(blank=True, null=True),
        ),
    ]
