# Generated by Django 5.2.6 on 2026-01-17 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_mt5account_breach_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='mt5account',
            name='trading_days',
            field=models.IntegerField(default=0),
        ),
    ]
